# Generated by Django 5.2.17 on 2026-09-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="reported_by_name",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
    ]
