# Generated by Django 5.2.17 on 2026-09-21 06:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_ticket_reported_by_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="last_activity_at",
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
